version: '3'

services:

  hyperf:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9501:9501"
    container_name: hyperf
    networks:
      - web-network
    volumes:
      - /home/docker/hyperf:/data/project
    privileged: true
    user: root
    stdin_open: true
    tty: true
    restart: always
  mysql:
    image: mysql:5.7
    volumes:
      - /home/docker/mysql:/var/lib/mysql

  nginx:
    image: nginx
    ports:
      - "80:80"
    container_name: nginx
    restart: always
    networks:
      - web-network
    #volumes:
      #- /root/web/nginx/nginx.conf:/etc/nginx/nginx.conf
      #- /root/web/nginx/logs:/etc/nginx/logs
      #- /root/web/nginx/www:/etc/nginx/www
      #- /root/web/nginx/conf:/etc/nginx/conf.d
    #depends_on:
   #

  redis:
    image: redis
    ports:
     - "6379:6379"
    container_name: redis
    networks:
     - web-network
    volumes:
     - redisdata:/data
    command: "redis-server --appendonly yes --requirepass 123456"
    restart: always
   
  mongo:
    image: mongo
    ports:
     - "27017:27017"
    container_name: mongo
    networks:
       - web-network
    restart: always
    privileged: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    volumes:
      - mongodata:/data/db
 
networks:
  web-network:
    external: true
    
volumes:
  redisdata:
  mongodata:
    #
    #
    #
